FROM debian:stretch-slim
LABEL Description="Image for checking out updater-repo"

RUN sed -i 's#deb http://deb.debian.org/debian stretch main#deb http://deb.debian.org/debian stretch main contrib#g' /etc/apt/sources.list
RUN sed -i 's#deb http://deb.debian.org/debian stretch-updates main#deb http://deb.debian.org/debian stretch-updates main contrib#g' /etc/apt/sources.list
RUN apt-get update -q && apt-get install -qy \
    git \
    repo \
    xmlstarlet
