#!/bin/sh
### BEGIN INIT INFO
# Provides:          touch-ostree
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Indicate OSTree boot
### END INIT INFO

case "$1" in
  start)
        touch /run/ostree-booted
        ;;
  stop)
        ;;
  *)
        echo "Usage: /etc/init.d/touch-ostree {start|stop}"
        exit 1
        ;;
esac
